### ISSUE TITLE
算法应用性

### ISSUE THREAD

**Issue by xiaobailaibaodao** [wenhaomin/graph2route#1]
请教个问题哈，不知道算法是否应用解决实际问题了呢？外卖场景订单量大，更新时间快，算法性能是否满足呢？

**Comment by wenhaomin** [comment]
你好，感谢你的提问。（1）这个算法目的是解决源于真实场景的问题，因此我们也在真实业务场景（物流场景）中检验了算法效果。（2）关于算法的性能，模型主要的时间开销在线下训练（training），线上推导（inference）速度实际很快，所以基本能够满足性能要求。此外，在实际应用时还可根据场景性能需求进行优化。
