### ISSUE TITLE
请求获取未脱敏数据，以及数据处理过程

### ISSUE THREAD

**Issue by wengaiDY** [wenhaomin/graph2route#4]
您好！源码中只有已经处理过的npy文件，请问food_pd npy所使用的未脱敏数据是怎么样的呢，又是如何将其处理成现在的npy文件呢？

**Comment by wenhaomin** [comment]
您好，food_pd使用的是饿了么天池骑士行为预估数据，数据的细节可以在其官网上找到：
https://tianchi.aliyun.com/competition/entrance/231777/introduction
数据的处理过程您可以给我邮箱，我们通过邮件发您。

**Comment by wenhaomin** [comment]
嗯嗯，是的，我们使用的就是比赛的数据。关于log_time，那个就是记录这条结果产生的时间。
