### ISSUE TITLE
Requesting the food_pd dataset

### ISSUE THREAD

**Issue by Deus-Ares** [wenhaomin/graph2route#6]
Hello! 
Is it possible to share the processed food_pd dataset used in the experiments  of the graph2route paper? 
or else can you please share with me the processing steps of the food_pd dataset. My email is yasassanwinchester@gmail.com. 
TIA!

**Comment by wenhaomin** [comment]
Hello, thanks for asking. The file size of the dataset is very large, therefore we didn't put it in github. I've sent you the code for generating the dataset. Please have a check.
