### ISSUE TITLE
数据处理过程咨询

### ISSUE THREAD

**Issue by wakk8** [wenhaomin/graph2route#8]
作者您好，您的工作很有创新性！我想了解一下其中的数据集是如何处理的呢？另外对于edge的特征edge absolute geodesic distance和 edge relative geodesic distance您是如何定义的呢？以及task的数量N是否是固定的呢，如果不是，那么当新的task出现，对于node和edge如何作相应的处理呢？我的邮箱是：1819124370@qq.com，十分感谢！

**Comment by wenhaomin** [comment]
同学您好，感谢留言。edge absolute distance是直接计算两个点在空间中的距离，edge relative geodesic distance 是两个订单的直线距离 / 快递员平均每天在两个订单间的行驶距离。不同样本的task数量不同，但是为了训练方便，对所有样本进行padding处理到相同的值。数据处理代码已经发送到邮箱，请查收。

**Comment by wakk8** [comment]
收到，谢谢作者！
